### ISSUE TITLE
Allow multipart/form-data file uploads

### ISSUE THREAD

**Issue by pnispel** [procore/js-sdk#13]
right now the only allowed `content-type` is `application/json` https://github.com/procore/js-sdk/blob/master/lib/client.ts#L50 as the headers aren't overridable, but for `multipart/form-data` the `content-type` header needs to not be set since the browser will take care of adding the boundary to the `content-type` (e.g. `multipart/form-data; boundary=----WebKitFormBoundaryfB2NtLKSbqM4j1eJ`)

**Comment by gilmcquillan** [comment]
This support was added in version 3.0.2. The following should allow you to update the Content-Type of the request.

```javascript
const procoreClinet = client(authorizer, {headers: {"Content-Type":"multipart/form-data"}});
```
