### ISSUE TITLE
Allow empty body response for status 204

### ISSUE THREAD

**Issue by dancingshell** [procore/js-sdk#17]
### Problem
Currently the response parser calls `response.json()` to get the body from the Stream. If the response is empty (as is expect for status `HTTP 204 No Content`) calling `.json()` will throw the error `Unexpected end of JSON input`.

### Current Workaround
Return empty `[]` or `{}` from the offending endpoint.

### Proposed solution
We should skip the call to `.json()` for requests expected to return no data and either return `null` or `{}` for the body

https://github.com/procore/js-sdk/blob/master/lib/client.ts#L67

https://stackoverflow.com/questions/37280029/whatwg-fetch-fails-when-json-parsing-an-empty-response-how-can-i-prevent-it

**Comment by scottwalstead** [comment]
@dancingshell Ran into this problem too and I'm going to fix it today

**Comment by dancingshell** [comment]
Fixed by #22
