### ISSUE TITLE
running yarn endpoints throws an error

### ISSUE THREAD

**Issue by scottwalstead** [procore/js-sdk#20]
Failed to fetch and parse JSON for endpoint: line item types (cost types) failed at step: Fetch
(node:28395) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token < in JSON at position 0
(node:28395) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cepm-nate** [comment]
Looks like I ran into the same thing: https://github.com/procore/js-sdk-endpoints/issues/9.

I think it's due to a few of their JSON files missing. Support mentioned someone would take a look at it.

**Comment by Varomir** [comment]
We are going to remove dependency to `js-sdk-endpoint` library at `js-sdk` version `3.0.0` at all.
Here is the PR: #42

**Comment by gilmcquillan** [comment]
PR https://github.com/procore/js-sdk/pull/42 removed js-sdk-endpoint support.
