### ISSUE TITLE
Issue with running yarn endpoints multiple times

### ISSUE THREAD

**Issue by scottwalstead** [procore/js-sdk#21]
Running yarn endpoints more than once seems to add the endpoints to index.ts regardless of whether they are already there leading to an error on yarn compile for duplicate declarations

lib/index.ts(9,21): error TS2300: Duplicate identifier 'projectRoles'.
lib/index.ts(10,21): error TS2300: Duplicate identifier 'me'.
lib/index.ts(11,21): error TS2300: Duplicate identifier 'programs'.
lib/index.ts(12,21): error TS2300: Duplicate identifier 'authentication'.

**Comment by gilmcquillan** [comment]
`yarn endpoints` has been removed in PR https://github.com/procore/js-sdk/pull/43
