### ISSUE TITLE
what are the values of action parameter?

### ISSUE THREAD

**Issue by saostad** [procore/js-sdk#29]
Hi,

I am trying to get list of projects from api but it seams in an action parameter is required but I couldn't figure out what are the possible values can be.

```
const { body } = await procore.get(
      projects({ action: "", qs: { company_id: process.env.COMPANY_ID } }),
    );
```

**Comment by yordis** [comment]
Reading this https://developers.procore.com/reference/projects,

Your call seems to be right

**Comment by nlovelace** [comment]
Anyone from Procore care to chime in? These two comments have only been on here for **1.5 YEARS** without a reply. If you're going to require them in your code then you should at least document it OR reply to this thread for other users.

**Comment by gilmcquillan** [comment]
The following example has been added to the README.md. You can just update the company_id qs value and the companyId config value.

```javascript
const procore = client(authorizer);
async function getProjects() {
  const { body, request, response } = await procore
    .get({
      base: '/projects',
      qs: { company_id: 1 }
    },
    {
      companyId: 1
    })
    .catch(error => {
    // Handle error
    console.log(error);
  });
  console.log(body[0].name); // ACME Construction LLC.
  console.log(response.headers.get('Total')) // 865 (Total records for the resource)
}
getProjects();
```
