### ISSUE TITLE
New CSRF strategy

### ISSUE THREAD

**Issue by nsinotov** [procore/js-sdk#41]
We are currently working on changing CSFR strategy in the scope of https://procoretech.atlassian.net/browse/VM-525
Would it be possible to change `csrf token` definition method here `lib/csrf.ts` to take it from cookie? For example like this `document.cookie.match('(^|;)\\s*csrf_token\\s*=\\s*([^;]+)')` and decode it after like this `decodeURIComponent(csrfTokenFromCookie)`. Else we need to implement it in every hydra client which is using `js-sdk` library.

**Comment by gilmcquillan** [comment]
This issue was resolved in this commit https://github.com/procore/js-sdk/commit/4371ee3bc64e90fbdea27c4066cefdcd439b2c70 in this PR https://github.com/procore/js-sdk/pull/42
